server:
   port: ${PORT:8082}
spring:
   data:
      mongodb:
         host: ${RISK_DB:localhost}
         port: ${RISK_DB_PORT:27019}
         database: ${RISK_DATABASE:risk}
         username: ${RISK_USERNAME:risk}
         password: ${RISK_PASSWORD:risk2020*}
# LOGGING
logging:
   level:
      com.riskmap.api: INFO
      org.springframework.web: ERROR
   file: logs/risk-service.log
   pattern.file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
   file.max-size: 50MB